#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruben8224-deployment
spec:
  selector:
    matchLabels:
      app: ruben8224-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ruben8224-server
    spec:
      containers:
      - name: ruben8224-container
        #image: gcr.io/tensorflow-serving/resnet
        image: docker.io/ruben8224/fastapiml:tagname
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ruben8224-service
  name: ruben8224-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ruben8224-server
  type: LoadBalancer